### ISSUE TITLE
alpha 7

### ISSUE THREAD

**Issue by phil-barrett** [terjeio/Grbl-GCode-Sender#11]
Tried Alpha 7.  Still hangs on first run against newly rebooted teensy4. Tried all three possible toggle actions.  Didn't see any different behavior with each.

Would be nice to be able to change port and toggle from the app.  deleting app.config gets old fast.

**Comment by terjeio** [comment]
Which Windows version?  I am running Win7. Driver:

![bilde](https://user-images.githubusercontent.com/20260062/75056832-10380f80-54d8-11ea-96b6-e036362997f7.png)

For [selecting port on startup](https://github.com/terjeio/Grbl-GCode-Sender/wiki/Setup-and-configuration): create a shortcut to the exe-file and add -selectport to the command line (target).

**Comment by phil-barrett** [comment]
Win 10. Teensy install says I don't need an update.
![GCode freeze 2](https://user-images.githubusercontent.com/16570958/75063015-caa82200-5498-11ea-83d6-377a8a6b4560.png)

**Comment by terjeio** [comment]
Then I guess it must be the driver causing this problem. I will investigate.

**Comment by terjeio** [comment]
Toggling DTR twice seems to have solved the issue with the Windows driver on Win10.

I have just started a 10-12 hours job on my Win10 machine that I'll run overnight to see if I can reproduce your communication glitch.

Too bad you fried your Teensy - you did that while trying too hook up the UART <> serial breakout?

**Comment by phil-barrett** [comment]
OK, looking forward to trying it out.  

Yup, not sure what I did.  The USB serial device was working fine looped back (tx to rx) but when I hooked it up the teensy, my PC barfed on it.  Oh well, shit happens.
