### ISSUE TITLE
4 axis visual glitches

### ISSUE THREAD

**Issue by phil-barrett** [terjeio/Grbl-GCode-Sender#14]
not urgent but for reference.
![4 axis glitch](https://user-images.githubusercontent.com/16570958/75592120-5809ea00-5a36-11ea-87d2-fdeddcbb42fe.png)

**Comment by terjeio** [comment]
Next alpha version hides (for now) _Program limits_ if  `N_AXIS` > 3, will expand jog panel later. Do we want keyboard jogging for A, B and C axes? Use `<Alt Gr>` and bind to cursor keys?

I hope I am able to publish next alpha later today - testing takes a lot of time...

**Comment by phil-barrett** [comment]
I may be missing something but did you not release a .exe?

**Comment by terjeio** [comment]
I did, all can be found via the [Releases](https://github.com/terjeio/Grbl-GCode-Sender/releases) icon on the main page:
![bilde](https://user-images.githubusercontent.com/20260062/76188211-d6555180-61d7-11ea-8f21-21de4cdd97f0.png)

**Comment by phil-barrett** [comment]
My bad.  sorry.  Installed and starting an overnight run.
