### ISSUE TITLE
alpha 10 issues

### ISSUE THREAD

**Issue by phil-barrett** [terjeio/Grbl-GCode-Sender#15]
Running a long test job (concentric_circles as arcs fr5000.cnc, posted on theGRBL/HAL issues list) with Aggressive Buffering and GCode Viewer on had a hang fairly early in the run.  Also, running same test job with GCode Viewer on by Aggressive Buffering off also hung.  A run with both off ran nearly to completion (7:05, 65K lines of 67.5K) but I tried to hold it and was unable restart.

**Comment by terjeio** [comment]
I guess this is fixed.
