### ISSUE TITLE
refresh button on com port selection

### ISSUE THREAD

**Issue by jschoch** [terjeio/Grbl-GCode-Sender#2]
you have to restart if you startup and have not yet plugged in your grbl.  Refresh button would be nice.

**Comment by terjeio** [comment]
Are you using COM-port streaming? If so I guess you mean a refresh button in the small dialog for selecting the com port. I will add a refresh button there, or perhaps better auto refresh on combo box drop event.

**Comment by terjeio** [comment]
Next build will auto-refresh com ports when the combo-box is opened.
