### ISSUE TITLE
another GCode file extension - .ngc

### ISSUE THREAD

**Issue by phil-barrett** [terjeio/Grbl-GCode-Sender#20]
Used by F-Engrave and several other tools from Scorch Works.

**Comment by terjeio** [comment]
Funny, I added this a few days ago - so will be available in next release. Be aware that if using _File > Open_ instead of drag&drop you have the option to select _All files (\*.\*)_ as a filter.

**Comment by phil-barrett** [comment]
Great minds think alike.

Yes, I've been using  _all files_   I tend not to use D&D.
