### ISSUE TITLE
A17: feed rate update problem

### ISSUE THREAD

**Issue by phil-barrett** [terjeio/Grbl-GCode-Sender#30]
This may be related to my previous report.

In the main TSender screen with no program running, highlight the number (0) in the Feed rate box and type any number. The display will not change.  Then, load and run a GCode file.  Note that the Feed rate in the display box stays at 0. Note that typing anything other than numeric digits will not cause this problem.  A restart is required to get the Feed rate to display correctly.

**Comment by terjeio** [comment]
Will fix in next release, have made the field non-focusable to avoid this (same as for the Program limits fields). It is already read-only so a bit strange that it fails to update after focused - might look into that later as well.
