### ISSUE TITLE
probe feedback "select type of probe"

### ISSUE THREAD

**Issue by jschoch** [terjeio/Grbl-GCode-Sender#33]
I finally got around to testing some probing.  I setup for center finding but it kept saying "select type of probe" and it took me a while to figure out what it wanted.  Maybe it should say "click probe type image to select probe movement"  or something more descriptive.

**Comment by terjeio** [comment]
I have added more descriptive messages:

* Edge finder: _Select edge or corner to probe by clicking on the relevant part of the image above._

* Center finder: _Select type of probe by clicking on one of the images above._

Hopefully this is better.

**Comment by jschoch** [comment]
Nice!
