### ISSUE TITLE
wiki updates

### ISSUE THREAD

**Issue by jschoch** [terjeio/Grbl-GCode-Sender#37]
I'd like to document a few things, how do you want to do that.  Should I do it via a pull request?

**Comment by terjeio** [comment]
It seems that using pull requests for the wiki is a [somewhat convoluted](https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github) process. Inviting you as a collaborator is perhaps easier? What do you think?

**Comment by jschoch** [comment]
what ever is easier for you.
