### ISSUE TITLE
Suggestion: make the latest version easier to find

### ISSUE THREAD

**Issue by phil-barrett** [terjeio/Grbl-GCode-Sender#43]
As interest in this program increases, a download link to the current executable version on the "front" page of this repository would make it easier to find. Perhaps the pre-built binary should be included in the project so that "clone or download" gets it as well. Anything to reduce confusion will increase the number of people using it.

Also, I think a download link to the latest version on the grblHAL repository "front page" would also be very helpful.  Alpha 19 is very stable and high quality.  It is far better than any other G Code Sender out there and will make it easier to use grblHAL.

**Comment by terjeio** [comment]
First has been fixed by github putting up a more prominent link to releases on the front page. And I have added a link to the sender from the grblHAL front page.
