### ISSUE TITLE
Beta Release: clicking on probe tab causes sender to exit.

### ISSUE THREAD

**Issue by phil-barrett** [terjeio/Grbl-GCode-Sender#48]
Problem: clicking on probe tab causes sender to exit
To reproduce: Start G Code Sender. Verify it is working. Click on Probe tab.

**Comment by terjeio** [comment]
Does not happen for me, perhaps a Win10 issue? No error messages?

**Comment by phil-barrett** [comment]
Hmmm, just tested it now and it does not happen. Not sure what was happening earlier.  There was not message, just a short pause, about 1 second, and then TSender exited.

**Comment by phil-barrett** [comment]
Not reproducible. will open new issue if it repeats.
