### ISSUE TITLE
Beta 4 crashes while startup - Teensy 4.1

### ISSUE THREAD

**Issue by einencool** [terjeio/Grbl-GCode-Sender#56]
@terjeio 
Hello Terje, 
I tried starting your Beta 4, but when the program shows up, it closes a few seconds later without a warning.

This is with the teensy 4.1, but I can't give you more input...

**Comment by terjeio** [comment]
It is a Win10 issue, with luck I may be able to upload a fix it later in the evening. Use Beta 3 until fixed.

**Comment by terjeio** [comment]
Fixed in Beta 5 - now up.
