### ISSUE TITLE
starting Shortcuts after Probing not working

### ISSUE THREAD

**Issue by einencool** [terjeio/Grbl-GCode-Sender#70]
Hello @terjeio 
I'm using the Sender 7.1 from your Web Site.
You added the possibility to start the Macros while in the Probing tab.
That works great, but I think there is a little issue.

When the probing is done, for me it's not possible to start a macro (F1 / F2 and so on) or activate the "Jogging function" with the "Ctrl + Shift" key.

I've tried it with my Keypad and directly from my keyboard, both don't work directly

First I have to click on a button or change to other tabs, so that it will work.
Can you please have a look at this?

**Comment by terjeio** [comment]
It works for me. Is this happening after any probing, e..g center finder, or just some probing actions?
Note that after probing G91 is active so all movements in a macro will be relative to the current position, add G90 to the start of the macro to avoid that for now. I'll fix that later.

I have uploaded a new edge version - only minor changes in that, the most important is that the _Goto_ flyout buttons are disabled until the machine is homed.

**Comment by einencool** [comment]
I had this several times, and I often used the outer edge finding.
It was not every time, sometimes it worked after the probing was complete.

Normally my workflow is the following one:
- Go to Probing tab edge finder
- Press „Ctrl + shift“ on XBOX Controller Button for jogging
- Jog to desired position for heigth probing
- Press „F1“ key and „Enter“ for Macro with Z-heigth probe
- After that move to desired Probing position (Edge Finder) 
- Activate the desired Corner in the Sender Tab
- Press „ALT + R“

After Probing I normally have to Offset my 3D-Finder for that I want to start my Macro „F2“
But often then the Software does not recognize any keypress. Even the „CTRL + SHIFT“ Shortcut doesn‘t work.
I have to click any button in the Software, then it works like it should.

Maybe I‘m doing something wrong, but I‘ll test your new Version at the weekend.

Thank you in advance :-)

**Comment by terjeio** [comment]
Ok, something must be taking focus away from the tab. Can you try to click in one of the fields, say _Rapids Feed Rate_ when this happens? Does the shorcuts work after doing that?

After testing I managed to replicate the behaviour - the main tabviewer got a dotted box around when it happened, this means the  it "stole" the focus. Seems like \<Alt\>+\<R\> triggers this but not always.

**Comment by einencool** [comment]
Hi @terjeio 
Like I mentioned before, you're right. When I press in any field or a button, then I'm able to start the macros with Shortcuts.

I'm a little bit scared, that the "Start Probing" Button has the same Shortcut like the "Normal G-Code Start" Button, but I think it is not possible, that it will start the GCode while in Probing tab...
Because I have mapped the Key to my XBOX Controller and I have to be very careful, not to press this Button while taking the Controller in hands.
Maybe in the future you could add an extra Clickbox like for the Shortcuts (F1 / F2 etc.) 
It could be usefull if this could be activated in the Settings. Because I think for me, it would be a great addition of Safety, but for most people it would be only one extra click without a positive benefit...

**Comment by terjeio** [comment]
I have tried to fix this issue with no luck so far, I'll keep trying. Sometimes the WPF framework can be frustrating to work with...

> I'm a little bit scared, that the "Start Probing" Button has the same Shortcut like the "Normal G-Code Start" Button, but I think it is not possible, that it will start the GCode while in Probing tab...

Not possible, shortcut handling is local to the tab that is active/visible and has focus.

> Maybe in the future you could add an extra Clickbox like for the Shortcuts (F1 / F2 etc.)

I'll think about it - however, since two keys needs to be pressed at the same time to activate these commands I do not believe it is necessary.

**Comment by einencool** [comment]
> I have tried to fix this issue with no luck so far, I'll keep trying. Sometimes the WPF framework can be frustrating to work with...

Thank you for this, maybe you‘ll find it in the future :-)


> > I'm a little bit scared, that the "Start Probing" Button has the same Shortcut like the "Normal G-Code Start" Button, but I think it is not possible, that it will start the GCode while in Probing tab...
> 
> Not possible, shortcut handling is local to the tab that is active/visible and has focus.

OK, that‘s a good point :-)

> > Maybe in the future you could add an extra Clickbox like for the Shortcuts (F1 / F2 etc.)
> 
> I'll think about it - however, since two keys needs to be pressed at the same time to activate these commands I do not believe it is necessary.

Yes, you‘re right, and that‘s why I said, for most Users it‘s just a click more. 
In my case, I have mapped the Shortcut „ALT + R“ or what it is, to ONE Button on my XBOX Controller.
So I have to press only one key, and I don‘t have so much keys, that I can use it with two buttons...
And then maybe you can understand my thougths about the „extra Clickbox“ because I‘ve also mapped the „Enter“ Key to one XBOX Button and then I can validate that I WANTET to press the button *g*

**Comment by terjeio** [comment]
> And then maybe you can understand my thougths about the „extra Clickbox“ because I‘ve also mapped the „Enter“ Key to one XBOX Button and then I can validate that I WANTET to press the button

I did not think about that, I'll make confirmation an option later.

I believe I have managed to fix the shortcut issue, new edge version just uploaded for you to test.

**Comment by einencool** [comment]
> I did not think about that, I'll make confirmation an option later.

Thank you for this :-) That would be really great, because when I‘m in the Probing tab, I need the Button for Probing, but in the „normal“ tab it‘s a bit scary, when the machine could start the job, when you touch the button, but it was not planned to touch it...
 
> I believe I have managed to fix the shortcut issue, new edge version just uploaded for you to test.

I‘ll try it at the weekend, maybe I‘ll get some time before. That‘s always the Problem, when the machine is not standing at home :-(

Thank you for your great support 🥇

**Comment by einencool** [comment]
Hello @terjeio 
Today I made a few tests with your new Version, and it seems, that it works now without any problems.
Last time it was around every second time, and today after 6 times it works every time.
Thank you for your support, so I‘ll close this issue now :-)
