### ISSUE TITLE
visual studio (2019) neophyte building 

### ISSUE THREAD

**Issue by jschoch** [terjeio/Grbl-GCode-Sender#8]
Well, I installed VS and my computer has been BSOD'ing for a week.  I think it has finally stabalized with some ram settings.

I tried to build the project and my newbness with both VS and c# are glaring.  I will try to read some tutorials on c#.  Any tips you might the build would be helpful.

here are the errors:

<img width="1920" alt="vs hell" src="https://user-images.githubusercontent.com/20271/73545883-15320380-43f1-11ea-8138-933ed0ed9b6b.png">

**Comment by jschoch** [comment]
i forgot to do a clean pull between VS19 and my attempts to get VS Code working.

also it seems that you have to nuget install the packages for each dependency not just in the main proj thingy.

Trying to work these out now.


<img width="1883" alt="vs hell2" src="https://user-images.githubusercontent.com/20271/73548492-bae77180-43f5-11ea-819e-5558388c244c.png">

**Comment by jschoch** [comment]
deleting the "CNC Core/obj" dir seems to have removed the issues for building core.

**Comment by jschoch** [comment]
i had to delete the obj dirs for all the dependencies and it built!!! 

I'll close this out now.

**Comment by terjeio** [comment]
See [wiki](https://github.com/terjeio/Grbl-GCode-Sender/wiki/Building) for dependencies.

Just saw your latest messsage, great you got it working.

I uploaded a new version yesterday, it does not look like you have downloaded that.
