### ISSUE TITLE
 Invert Spindle Signals ($16) issues

### ISSUE THREAD

**Issue by phil-barrett** [terjeio/Grbl-GCode-Sender#82]
Using Beta 8 release.

Invert Spindle Signals ($16), Spindle On, bit 0, confuses ioSender at start up after a power cycle.  ioSender sees the spindle  as on initially (but it is not).  Clicking on Off gets ioSender back in sync.

There is also some strange behavior when you switch enable invert while running the spindle. grblHAL (or ioSender?) thinks running is stopped and vice versa.  Probably unrelated and not a good idea to do on a real machine with a live spindle. Maybe there should be a warning about inadvertent spindle start up?

A suggestion:  In Settings:Grbl, Invert Spindle Settings, change Spindle CCW to Spindle Direction and change Spindle On to Spindle Enable.  (though Spindle On vs Enable is debatable and On says what it actually does, Enable seems to be the more common usage.)

**Comment by terjeio** [comment]
I have rephrased the labels in the latest grblHAL test branch build and removed the invert PWM option if driver support is not available.
